edition = "2021"
hard_tabs = true
max_width = 100
tab_spaces = 4
reorder_imports = true
match_block_trailing_comma = true
newline_style = "Unix"
reorder_modules = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
